# application.properties
# secret이 붙은 설정 파일을 같이 로드하겠다는 의미입니다.
spring.profiles.include=secret

# 2. HikariCP 설정
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.data-source-properties.oracle.net.tns_admin=D:/util/Wallet_C6WGI06XVMDIACVS
spring.datasource.hikari.data-source-properties.oracle.net.ssl_server_dn_match=true

# 3. MyBatis 설정
mybatis.mapper-locations=classpath:mappers/**/*.xml
mybatis.configuration.log-impl=org.apache.ibatis.logging.nologging.NoLoggingImpl
# DB에서 꺼내올 때 대문자를 소문자 카멜케이스 맵으로 자동 변환 (2번 설정)
mybatis.configuration.map-underscore-to-camel-case=true

# [추가] 커넥션이 맺어질 때마다 병렬 DML을 강제로 차단하는 세션 스위치 작동 (권한 에러 안 남)
spring.datasource.hikari.connection-init-sql=ALTER SESSION DISABLE PARALLEL DML
