# 🌟 중요: 오라클 19c 클라우드 보안 연동을 위해 아래 2줄을 추가합니다.
spring.datasource.oracle.net.tns_admin=D:/util/Wallet_C6WGI06VMDIACVS
spring.datasource.oracle.net.ssl_server_dn_match=true

# SSL/보안 설정 추가 (지갑 사용 시 필수)
spring.datasource.hikari.maximum-pool-size=5

# 🌟 오라클 19c 전자지갑 연동 표준 규격
#spring.datasource.url=jdbc:log4jdbc:oracle:thin:@c6wgi06xvmdiacvs_high?TNS_ADMIN=D:/util/Wallet_C6WGI06XVMDIACVS
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy


# 1. 드라이버와 URL을 log4jdbc가 없는 순정 오라클로 변경합니다.
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@c6wgi06xvmdiacvs_high?TNS_ADMIN=D:/util/Wallet_C6WGI06XVMDIACVS


spring.datasource.username=ADMIN
spring.datasource.password=rlaqudwnFkdlxmsld!1

# 마이바티스 매퍼 위치
# 파일 탐색기에서 보신 폴더명이 mapper라면 무조건 mapper로 적어야 합니다.
mybatis.mapper-locations=classpath:mappers/**/*.xml


logging.level.com.nyang.drip.board.mapper=INFO
# 1. MyBatis가 실행하는 쿼리(실행 코드)를 INFO 레벨로 출력합니다.
# (★주의: com.nyang.drip.board.mapper 부분은 본인의 Mapper 인터페이스가 있는 패키지 경로와 정확히 일치해야 합니다!)
logging.level.com.nyang.drip.board.mapper=DEBUG
# 2. 스프링 부트 내부의 JDBC 템플릿/스테이트먼트 쿼리 수행 로그도 켜줍니다.
logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG